---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c release --no-restore
